server:
  port: 800

spring:
  devtools:
    restert:
      enabled: true


  datasource:
    username: "root"
    password: "1234"
    url: "jdbc:mysql://localhost:3306/curs?serverTimezone=UTC"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    hibernate:
      ddl-auto: "update"
